test("Test", () => {

});

test("FailTest", () => {
    throw new Error("Fail !");
});